name: Notify on Push

on:
  push:
    branches:
      - main  # ou la branche de votre choix

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Envoyer un e-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Nouveau commit sur le projet"
          body: "Un nouveau commit a été effectué par un collaborateur."
          to: "votre.email@example.com"
          from: "noreply@example.com"
