name: Push Notification

on: 
  push: # S'exécute sur les pushs sur toutes les branches
    branches: 
      - '**' # Cela signifie toutes les branches

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'Push Successful with Code Analysis'
          body: 'Le push sur la branche ${{ github.ref }} a été effectué avec succès !\n\nSuggestions d\"amélioration du code:\n${{ env.improved_code }}'
          to: ${{ env.userEmail }}
          from: 'latifnjimoluh@gmail.com' # Remplace par ton adresse e-mail
