name: Push Notification

on: 
  push: # S'exécute sur les pushs sur toutes les branches
    branches: 
      - '**' # Cela signifie toutes les branches

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com # Remplace par ton serveur SMTP
          server_port: 587 # Port du serveur SMTP
          username: ${{ secrets.SMTP_USERNAME }} # Utilisateur SMTP dans les secrets GitHub
          password: ${{ secrets.SMTP_PASSWORD }} # Mot de passe SMTP dans les secrets GitHub
          subject: 'Push Successful'
          body: 'Le push sur la branche ${{ github.ref }} a été effectué avec succès !'
          to: 'latifnjimoluh@gmail.com' # Remplace par l'adresse e-mail du destinataire
          from: 'latifnjimoluh@gmail.com' # Remplace par ton adresse e-mail
